name: CAN Bus Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install python-can pytest

      - name: Setup virtual CAN interface
        run: |
          sudo modprobe vcan
          sudo ip link add dev vcan0 type vcan
          sudo ip link set up vcan0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: pytest tests/
